sudo: required
language: elixir
elixir:
  - 1.3.4
services:
  - postgresql
  - docker
before_script:
  - psql -c 'create database registro_test;' -U postgres
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    all_branches: true
