use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :registro, :recaptcha,
  site_key: {:system, "RECAPTCHA_SITE_KEY"},
  secret_key: {:system, "RECAPTCHA_SECRET_KEY"}

config :registro, Registro.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: System.get_env("HOST") || "cruzroja.instedd.org", port: 80],
  secret_key_base: System.get_env("SECRET_KEY_BASE"),
  cache_static_manifest: "priv/static/manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Configure database
config :registro, Registro.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: System.get_env("DATABASE_USER") || "cruzroja",
  password: System.get_env("DATABASE_PASS"),
  database: System.get_env("DATABASE_NAME") || "cruzroja",
  hostname: System.get_env("DATABASE_HOST") || "localhost",
  pool_size: 10

# Configure coherence mailer
config :coherence, Registro.Coherence.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: {:system, "SMTP_RELAY"},
  username: {:system, "SMTP_USER"},
  password: {:system, "SMTP_PASS"},
  tls: :always,
  auth: :always
